#!/usr/bin/env python
# Copyright (C) 2015 Swift Navigation Inc.
# Contact: Bhaskar Mookerji <mookerji@swiftnav.com>
#
# This source is subject to the license found in the file 'LICENSE' which must
# be be distributed together with this source. All other rights reserved.
#
# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.

R2D_ = R2D
D2R_ = D2R

GPS_PI_ = GPS_PI
GPS_L1_HZ_ = GPS_L1_HZ
GPS_OMEGAE_DOT_ = GPS_OMEGAE_DOT
GPS_GM_ = GPS_GM
GPS_C_ = GPS_C
GPS_F_ = GPS_F
GPS_C_NO_VAC_ = GPS_C_NO_VAC
GPS_L1_LAMBDA_ = GPS_L1_LAMBDA
GPS_L1_LAMBDA_NO_VAC_ = GPS_L1_LAMBDA_NO_VAC
GPS_NOMINAL_RANGE_ = GPS_NOMINAL_RANGE
GPS_CA_CHIPPING_RATE_ = GPS_CA_CHIPPING_RATE

DEFAULT_PHASE_VAR_TEST_ = DEFAULT_PHASE_VAR_TEST
DEFAULT_CODE_VAR_TEST_ = DEFAULT_CODE_VAR_TEST
DEFAULT_PHASE_VAR_KF_ = DEFAULT_PHASE_VAR_KF
DEFAULT_CODE_VAR_KF_ = DEFAULT_CODE_VAR_KF
DEFAULT_AMB_DRIFT_VAR_ = DEFAULT_AMB_DRIFT_VAR
DEFAULT_AMB_INIT_VAR_ = DEFAULT_AMB_INIT_VAR
DEFAULT_NEW_INT_VAR_ = DEFAULT_NEW_INT_VAR
