.PHONY: clean All

All:
	@echo "----------Building project:[ l2cbitstream_test - Debug ]----------"
	@cd "l2cbitstream_test" && "$(MAKE)" -f  "l2cbitstream_test.mk"
clean:
	@echo "----------Cleaning project:[ l2cbitstream_test - Debug ]----------"
	@cd "l2cbitstream_test" && "$(MAKE)" -f  "l2cbitstream_test.mk" clean
