#!/bin/sh
#
# Based on setlocalversion from the Linux kernel.
#

# Check for git and a git repo.
if head=`git rev-parse --verify --short HEAD 2>/dev/null`; then

  # If we are past a tagged commit (like "v2.6.30-rc5-302-g72357d5"),
  # we pretty print it.
  if atag="`git describe 2>/dev/null`"; then
    printf '%s' $atag
  # If we don't have a tag at all we print -g{commitish}.
  else
    printf '%s%s' -g $head
  fi

	# Check for uncommitted changes
	if git diff-index --name-only HEAD | grep -v "^scripts/package" \
	    | read dummy; then
		printf '%s' -dirty
	fi
else
  printf '%s' unknown
fi

